In [4]:
import pandas as pd
import numpy as np
from datetime import timedelta
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
calls = pd.read_csv('../Data/calls_clean.csv')
charts = pd.read_csv('../Data/charts_clean.csv')
geocode = pd.read_csv('../Data/geocodeclean.csv')

In [12]:
calls.head(25)

,Month,Precinct,Date,Created,Address,Incident Type,Priority
0,July,C,07-01-2021,01:57:16,639 LAFAYETTE ST,INTOXICATED PERSON,2
1,July,C,07-01-2021,03:02:52,920 BROADWAY,WELFARE CHECK,2
2,July,C,07-01-2021,05:44:47,110 4TH AVE S,DISORDERLY SUBJECT,2
3,July,C,07-01-2021,05:49:07,800 4TH AVE S,SUSPICIOUS PERSON,2
4,July,C,07-01-2021,08:01:06,1033 DEMONBREUN ST,TRESPASSER,2
5,July,C,07-01-2021,08:12:50,705 DREXEL ST,DISORDERLY SUBJECT,2
6,July,C,07-01-2021,08:28:36,127 4TH AVE S,DISORDERLY SUBJECT,2M
7,July,C,07-01-2021,09:05:14,206 3RD AVE S,DISORDERLY SUBJECT,2
8,July,C,07-01-2021,09:18:49,VICTORY AVE / S 1ST ST,DISORDERLY SUBJECT,2
9,July,C,07-01-2021,09:21:46,THE ARCADE,MENTAL CONDITION,3
10,July,C,07-01-2021,11:08:55,525 4TH AVE S,DISORDERLY SUBJECT,2M
11,July,C,07-01-2021,11:13:05,209 BROADWAY,TRESPASSER,2
12,July,C,07-01-2021,11:14:27,705 DREXEL ST,MENTAL CONDITION,2
13,July,C,07-01-2021,11:57:51,GEORGE L DAVIS BLVD / DR MARTIN L KING JR BLVD,ASSIST EMS,2M
14,July,C,07-01-2021,13:02:27,300 KOREAN VETERANS BLVD,TRESPASSER,2
15,July,C,07-01-2021,14:05:06,162 PRINTERS ALY,DISORDERLY SUBJECT,2
16,July,C,07-01-2021,14:06:23,1202 BROADWAY,ASSIST EMS,2
17,July,C,07-01-2021,14:08:06,1207 MCGAVOCK ST,SUICIDAL PERSON,2
18,July,C,07-01-2021,14:40:28,1002 DIVISION ST,SUSPICIOUS PERSON,2
19,July,C,07-01-2021,14:44:42,6TH AVE S / DEMONBREUN ST,ASSIST EMS,2M
20,July,C,07-01-2021,14:53:17,1ST AVE N / GAY ST,ASSIST EMS,2M
21,July,C,07-01-2021,15:19:05,400 DR MARTIN L KING JR BLVD,ASSIST EMS,2M
22,July,C,07-01-2021,15:30:16,639 LAFAYETTE ST,ASSIST EMS,2
23,July,C,07-01-2021,16:39:59,639 LAFAYETTE ST,SUICIDAL PERSON,2
24,July,C,07-01-2021,18:38:38,212 BROADWAY,DISORDERLY SUBJECT,2M

In [13]:
charts.head(25)

,Month,Precinct,ASSIST EMS,DISORDERLY SUBJECT,DOMESTIC DISTURBANCE,INTOXICATED PERSON,MENTAL CONDITION,SUICIDAL PERSON,SUSPICIOUS PERSON,TRESPASSER,...,Priority_2L,Priority_2M,Priority_2N,Priority_2T,Priority_2R,Priority_3,Priority_3H,Priority_3M,Priority_3Q,Total Response
0,August,C,203,354,11,7,28,43,18,104,...,0,251,0,0,0,21,0,1,0,853
1,August,CMD1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
2,August,CW,3,8,0,0,1,1,1,3,...,0,17,0,0,0,0,0,0,0,19
3,August,E,91,187,56,3,13,16,44,33,...,0,126,0,0,0,12,0,2,0,531
4,August,H,190,310,64,5,28,31,69,68,...,0,190,0,0,0,32,0,4,0,955
5,August,M,140,173,48,0,16,20,33,28,...,0,169,0,0,0,21,0,0,0,578
6,August,MT,164,255,31,6,21,19,50,67,...,1,186,0,0,0,23,0,0,0,742
7,August,N,141,236,70,1,22,29,32,46,...,0,143,0,0,0,40,0,0,0,706
8,August,PCW,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
9,August,S,190,304,77,8,23,23,45,66,...,0,180,0,0,0,41,0,2,0,908
10,August,W,124,160,18,5,17,17,36,38,...,0,114,0,0,0,23,0,1,0,513
11,December,C,140,264,12,7,18,30,16,134,...,0,172,0,0,0,25,0,0,0,706
12,December,CW,2,1,0,0,0,0,2,3,...,0,6,0,0,0,0,0,0,0,11
13,December,E,97,154,21,4,11,15,32,18,...,0,145,0,0,0,19,0,3,0,457
14,December,H,168,240,56,4,18,32,69,61,...,0,181,0,0,0,30,0,3,0,837
15,December,M,125,174,39,3,15,23,42,39,...,0,176,0,0,0,20,0,2,0,582
16,December,MT,122,191,34,3,15,22,42,58,...,0,188,0,0,0,17,0,0,0,616
17,December,N,125,161,35,1,18,20,35,55,...,0,126,0,0,0,35,0,5,0,565
18,December,S,158,270,57,1,14,23,45,56,...,0,184,0,0,0,36,0,0,0,848
19,December,W,101,128,16,2,6,13,46,34,...,0,101,0,0,0,19,0,3,0,474
20,February,C,126,251,9,10,14,48,14,90,...,0,166,0,0,0,27,0,0,0,625
21,February,CW,1,4,0,0,0,0,0,0,...,0,3,0,0,0,0,0,0,0,5
22,February,E,96,120,31,2,14,13,28,32,...,1,120,0,0,0,23,0,0,0,441
23,February,H,159,236,48,6,15,33,58,53,...,0,207,0,0,0,40,0,1,0,818
24,February,M,105,129,30,2,9,15,40,29,...,0,149,0,0,0,19,0,0,0,471

In [15]:
geocode.head(25)

                       address        lat        lng
0             1022 SEYMOUR AVE  36.185726 -86.750575
1            1310 EASTLAND AVE  36.183276 -86.745370
2                 617 S 5TH ST  36.165976 -86.760884
3              2409 EMMETT AVE  36.195349 -86.747668
4          2930 DICKERSON PIKE  36.223448 -86.761631
5          1407 DICKERSON PIKE  36.198205 -86.770692
6            2510 GALLATIN AVE  36.195992 -86.742208
7                  10 S 6TH ST  36.172935 -86.763300
8              757 DOUGLAS AVE  36.193831 -86.753383
9               685 JOSEPH AVE  36.182828 -86.772523
10             130 MERIDIAN CT  36.198059 -86.767967
11              570 JOSEPH AVE  36.180944 -86.772764
12           1701 EASTLAND AVE  36.183168 -86.739025
13             1135 KENWOOD DR  36.225807 -86.721380
14             923 DOUGLAS AVE  36.193278 -86.747825
15              2201 CHASE AVE  36.190394 -86.722971
16            4127 EDWARDS AVE  36.226137 -86.736589
17        272 DELLWAY VILLA RD  36.212940 -86.760363
18             1013 GRANADA CT  36.188341 -86.750143
19               719 NEILL AVE  36.184074 -86.759196
20  PAULAWOOD DR / OAKWOOD AVE  36.211178 -86.753669
21               1012 N 6TH ST  36.189158 -86.761533
22          4312 GALLATIN PIKE  36.225669 -86.724858
23             808 ROSEVIEW DR  36.186867 -86.708447
24  RR XING MCGAVOCK PIKE EAST  36.209983 -86.713114

In [16]:
#JOIN GEOCODE & CALLS DF

In [17]:
geo_calls_merged = pd.merge(geocode, calls,left_on = 'address', right_on = 'Address')
geo_calls_merged.drop(['address'], axis=1, inplace = True)
geo_calls_merged.head(10)

,lat,lng,Month,Precinct,Date,Created,Address,Incident Type,Priority
0,36.185726,-86.750575,October,E,10-06-2021,15:25:27,1022 SEYMOUR AVE,WELFARE CHECK,2M
1,36.185726,-86.750575,October,E,10-25-2021,02:10:19,1022 SEYMOUR AVE,DISORDERLY SUBJECT,2
2,36.185726,-86.750575,November,E,11-25-2021,15:58:50,1022 SEYMOUR AVE,DOMESTIC DISTURBANCE,2M
3,36.185726,-86.750575,December,E,12-03-2021,16:13:44,1022 SEYMOUR AVE,WELFARE CHECK,2
4,36.185726,-86.750575,December,E,12-20-2021,04:18:15,1022 SEYMOUR AVE,WELFARE CHECK,2
5,36.185726,-86.750575,December,E,12-24-2021,14:07:09,1022 SEYMOUR AVE,WELFARE CHECK,2
6,36.185726,-86.750575,March,E,03-14-2022,02:36:19,1022 SEYMOUR AVE,DISORDERLY SUBJECT,2
7,36.185726,-86.750575,March,E,03-25-2022,23:52:00,1022 SEYMOUR AVE,SUSPICIOUS PERSON,2
8,36.183276,-86.745370,October,E,10-06-2021,17:41:41,1310 EASTLAND AVE,DISORDERLY SUBJECT,1
9,36.183276,-86.745370,October,E,10-14-2021,06:09:12,1310 EASTLAND AVE,MENTAL CONDITION,2M